# docker compose extension for flower, the celery task monitor
services:
  celeryflower:
    environment:
      REDIS_URL: redis://redis:6379/0
    build:
      context: https://github.com/mher/flower.git#v0.9.2
    entrypoint: /bin/sh
    command: -c '
      flower
        --address=0.0.0.0
        --broker="$$REDIS_URL"
      '
    depends_on:
      - celeryworker
    ports:
      - target: 5555
        published: ${FLOWER_EXTERNAL_PORT:-5555}
    restart: unless-stopped
